name: domain
version: 0.0.1

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  data:
    path: ../data

  core:
    path: ../core

dev_dependencies:
  build_runner: ^2.1.7
  hive_generator: ^1.1.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
