name: core
version: 0.0.1

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.1
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  data:
    path: ../data
  domain:
    path: ../domain
  navigation:
    path: ../navigation
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: