name: core
version: 0.0.1

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.1
  firebase_auth: ^4.7.2
  google_sign_in: ^6.1.4
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  hive: ^2.2.3
  hive_flutter: ^1.0.0
  internet_connection_checker_plus: ^2.0.0
  shared_preferences: ^2.2.0
  cached_network_image: ^3.2.1
  adaptive_theme: ^3.3.0
  json_annotation: ^4.3.0
  freezed_annotation: ^2.2.0
  data:
    path: ../data
  domain:
    path: ../domain
  navigation:
    path: ../navigation
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: