name: food_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ./core
  data:
    path: ./data
  navigation:
    path: ./navigation
  domain:
    path: ./domain
  core_ui:
    path: ./core_ui

  cupertino_icons: ^1.0.2

dev_dependencies:
  mocktail: ^1.0.0
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
