name: navigation
version: 0.0.1

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  auto_route: ^5.0.4

  flutter:
    sdk: flutter
  dishes_view:
    path: ../features/dishes_view
  cart_view:
    path: ../features/cart_view
  settings_view:
    path: ../features/settings_view
  domain:
    path: ../domain
  core:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.7
  auto_route_generator: 5.0.3

flutter:
