name: navigation
version: 0.0.1

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  google_nav_bar: ^5.0.6
  flutter:
    sdk: flutter
  dishes_view:
    path: ../features/dishes_view

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
